version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    
    working_directory: ~/learning-spring

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout

      - restore_cache:
          key: spring-petclinic-clone-kotlin-{{ checksum "spring-petclinic-clone-kotlin/pom.xml" }}
      
      - run: mvn -f spring-petclinic-clone-kotlin/pom.xml dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring-petclinic-clone-kotlin-{{ checksum "spring-petclinic-clone-kotlin/pom.xml" }}
      
      - run: mvn -f spring-petclinic-clone-kotlin/pom.xml clean package
      
      - store_test_results:
          path: ~/learning-spring/spring-petclinic-clone-kotlin/target/surefire-reports
      
      - store_artifacts:
          path: ~/learning-spring/spring-petclinic-clone-kotlin/target/spring-petclinic-clone-kotlin-0.0.1-SNAPSHOT.jar
          
      - store_artifacts:
          path: ~/learning-spring/spring-petclinic-clone-kotlin/target/my-reports
          destination: code_coverage_report
                
      - store_artifacts:
          path: ~/learning-spring/spring-petclinic-clone-kotlin/target/jacoco.exec
          
      - codecov/upload:
          file: {{ "~/learning-spring/spring-petclinic-clone-kotlin/target/jacoco.exec" }}

