version: 2.1

jobs:
  build:
    
    working_directory: ~/learning-spring

    docker:
      - image: circleci/openjdk:11-stretch

    steps:

      - checkout

      - restore_cache:
          key: spring-petclinic-clone-kotlin-{{ checksum "spring-petclinic-clone-kotlin/pom.xml" }}
      
      - run: mvn -f spring-petclinic-clone-kotlin/pom.xml dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring-petclinic-clone-kotlin-{{ checksum "spring-petclinic-clone-kotlin/pom.xml" }}
      
      - run: mvn -f spring-petclinic-clone-kotlin/pom.xml clean package
      
      - store_test_results:
          path: /spring-petclinic-clone-kotlin/target/surefire-reports
      
      - store_artifacts:
          path: /pring-petclinic-clone-kotlin/target/spring-petclinic-clone-kotlin-0.0.1-SNAPSHOT.jar
