spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic_dev
    username: my_dev_user
    password: super_password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
